
# spring配置
spring:
  messages:
    encoding: utf-8
  banner:
    charset: UTF-8
  # 数据库连接
  datasource:
    name: mysql
    url: jdbc:mysql://akatosh.xyz:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # 文件上传
  servlet:
      multipart:
        max-file-size: 300MB
        max-request-size: 300MB
  devtools:
      restart:
        # 热部署开关
        enabled: true

# 端口号
server:
  port: 8302
